# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Souvik Mitra"
title_separator          : "-"
name                     : &name "Souvik Mitra"
description              : &description "Environmental Researcher | Climate-Smart Agriculture | Remote Sensing | Python & GIS"
url                      : "https://souvikmitra21.github.io"
baseurl                  : ""
repository               : "souvikmitra21/souvikmitra21.github.io"

# Author Sidebar Profile
author:
  avatar           : "profile.png"
  name             : "Souvik Mitra"
  pronouns         : "he/him"
  bio              : "Postgraduate in Environmental Science (BHU), passionate about climate-smart agriculture, solar energy systems, and geospatial analytics."
  location         : "Jharkhand, India"
  employer         : "Banaras Hindu University (Alumnus)"
  uri              : "https://souvikmitra21.github.io"
  email            : "mitrasouvik2001@gmail.com"

  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  orcid            :  # Add your ORCID URL when available
  researchgate     : "https://www.researchgate.net/profile/Souvik-Mitra"
  github           : "souvikmitra21"
  linkedin         : "souvik-mitra-313b3321a"
  twitter          : "MitraSouvik01"

# Publication Categories
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# Site Features
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false

comments:
  provider               :

atom_feed:
  hide                   : false
  path                   :

# Social Sharing
twitter:
  username               : &twitter "MitraSouvik01"

facebook:
  username               :

og_image                 :
og_description           :
social:
  type                   : "Person"
  name                   : "Souvik Mitra"
  links:
    - https://github.com/souvikmitra21
    - https://linkedin.com/in/souvik-mitra-313b3321a
    - https://scholar.google.com/citations?user=PS_CX0AAAAAJ
    - https://www.researchgate.net/profile/Souvik-Mitra

# Analytics (Optional)
analytics:
  provider               : "false"

# Include & Exclude
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Markdown & Processing
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Layout Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true

  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Output & Timezone
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
