# Basic Site Settings
locale                   : "en-US"
title                    : "Souvik Mitra"
title_separator          : "-"
name                     : &name "Souvik Mitra"
description              : &description "Environmental Researcher | UGC-NET | Data & GIS Enthusiast"
url                      : https://souvikmitra21.github.io
baseurl                  : ""
repository               : "souvikmitra21/souvikmitra21.github.io"

# Site Author
author:
  avatar: "images/profile.png"  # Make sure this file exists at /images/profile.png
  name        : "Souvik Mitra"
  bio         : "Environmental Researcher | Data Science | Remote Sensing | UGC-NET"
  location    : "India"
  employer    : "Independent Researcher"
  email       : "mitrasouvik2001@gmail.com"
  github      : "Souvikmitra21"
  linkedin    : "souvik-mitra-313b3321a/"
  kaggle      : ""  # Optional: provide URL or username if applicable
  orcid       : ""  # Optional: provide ORCID ID if you have one

 
# Site Settings
teaser                   :  # Add image filename if you want a default teaser image
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false

comments:
  provider               : false

atom_feed:
  hide                   : false

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :

social:
  type                   : Person
  name                   : "Souvik Mitra"
  links:
    - "https://github.com/Souvikmitra21"
    - "https://linkedin.com/in/souvikmitra21"

# Analytics
analytics:
  provider               : false

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  workexp:
    output: true
    permalink: /:collection/:path/collections:
  publications:
    output: true
    permalink: /publications/:name/
  awards:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: Publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: workexp
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: awards
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Asia/Kolkata

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
